version: 2
jobs:
    build:
        docker:
            -image: circleci/node:8.0
        steps:
            - checkout
            - run: 
                name: Install Deps
                command: yarn install